apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scrapeme.fullname" . }}-secrets
  labels:
    {{- include "scrapeme.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.config.env }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
