{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "scrapeme.fullname" . }}
  labels:
    {{- include "scrapeme.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.monitoring.serviceMonitor.namespace }}
  namespace: {{ .Values.monitoring.serviceMonitor.namespace }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "scrapeme.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
{{- end }}
