apiVersion: v1
kind: Service
metadata:
  name: {{ include "scrapeme.fullname" . }}
  labels:
    {{- include "scrapeme.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "scrapeme.selectorLabels" . | nindent 4 }}
