apiVersion: v2
name: scrapeme
description: A Helm chart for ScrapeMe - Selenium Automation Framework
type: application
version: 0.1.0
appVersion: "2.0.0"
dependencies:
  - name: selenium-grid
    version: 0.2.0
    repository: https://www.selenium.dev/helm-charts
    condition: selenium-grid.enabled
